# Generated by Django 4.2.5 on 2023-09-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolanarede', '0002_camisa_perfil_time_delete_camisas_camisa_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Usuario',
        ),
    ]
