# Generated by Django 4.2.5 on 2023-09-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolanarede', '0003_rename_perfil_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camisa',
            old_name='titulo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='time',
            name='email',
        ),
        migrations.AlterField(
            model_name='camisa',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camisa', to='bolanarede.time'),
        ),
    ]
