# Generated by Django 4.2.5 on 2023-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolanarede', '0004_rename_titulo_camisa_descricao_remove_camisa_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisa',
            name='wow',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
