# Generated by Django 4.2.6 on 2023-10-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolanarede', '0007_rename_camisa_camisa_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='site',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Favorito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='bolanarede.time'),
            preserve_default=False,
        ),
    ]
